// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEbTKMYHEzx0w1PhrSxzqTaWGs3ApZjic',
    appId: '1:477649048571:web:d10e7ef5ff1e5485a0315e',
    messagingSenderId: '477649048571',
    projectId: 'flutterprojectfinal-ec57e',
    authDomain: 'flutterprojectfinal-ec57e.firebaseapp.com',
    storageBucket: 'flutterprojectfinal-ec57e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFhOOgUx9w75EQTcVchVTUuphcfmlZBE',
    appId: '1:477649048571:android:021e6659c419731ea0315e',
    messagingSenderId: '477649048571',
    projectId: 'flutterprojectfinal-ec57e',
    storageBucket: 'flutterprojectfinal-ec57e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKcS4VWHnBVQ7_SWa3KiYNK-KdJvgmlk',
    appId: '1:477649048571:ios:e6709c5a477b8deea0315e',
    messagingSenderId: '477649048571',
    projectId: 'flutterprojectfinal-ec57e',
    storageBucket: 'flutterprojectfinal-ec57e.appspot.com',
    iosClientId: '477649048571-pu84qutf2jo2j5gpa8p1q2q7b6ep2014.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADKcS4VWHnBVQ7_SWa3KiYNK-KdJvgmlk',
    appId: '1:477649048571:ios:e6709c5a477b8deea0315e',
    messagingSenderId: '477649048571',
    projectId: 'flutterprojectfinal-ec57e',
    storageBucket: 'flutterprojectfinal-ec57e.appspot.com',
    iosClientId: '477649048571-pu84qutf2jo2j5gpa8p1q2q7b6ep2014.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
